---
title: "Introduction to R for Statistical Analysis"
author: "John Palmer"
date: "November 15, 2019"
output: 
  revealjs::revealjs_presentation:
    theme: night
    highlight: zenburn
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## What is R?

- R is a programming language and software environment for statistical computing and graphics
- It comes from the S language developed by John Chambers at Bell Laboratories in the 1970s
- R was created by Ross Ihaka and Robert Gentleman at the University of Auckland, New Zealand, starting in the 1990s. It is now developed by a larger community of developers (the R Development Core Team) supported by non-profit foundation (the R Foundation)
- Official home page is https://r-project.org/

## R is Free Software

- Being "free software" means users have the freedom to run, copy, distribute, study, change and improve R
- In other words, the "free" part is about liberty not price
- But R is also free in terms of price

## R Packages

- One of the powerful thing about R is the enormous ecosystem of packages that people have written for it
- An R package is a bundle of code, often along with data, documentation and tests, which runs in R and can be shared
- There are thousands of packages for R, written by people all over the world in a wide variety of disciplines, and mostly distributed under free and open source licenses
- You can easily install R packages from CRAN as well from GitHub and other code repositories


## Installing and Updating R

- You should already have it installed, but if not, go to https://cran.r-project.org/ and install the latest release that is compatible with your system
- R is being continuously developed and new versions are regularly released
- You do not need to upgrade every time there is a new version, but you will want to upgrade every so often in order to take advantage of new features or to ensure that you have a version that supports new packages
- If you already have a lot of packages that you rely on, you may want to copy them into the new version to avoid having to download them again
- It is also sometimes useful to have multiple versions of R installed side-by-side and this is possible
